# Autogenerated file
def render(*a, **d):
    yield """<!doctype html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\"
          content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">
    <title>IoT Control</title>

    <! -- FONTS GOOGLE -->
    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">
    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>
    <link href=\"https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap\" rel=\"stylesheet\">
    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons+Outlined\" rel=\"stylesheet\">

    <! -- STYLE CSS -->
    <link rel=\"stylesheet\" href=\"/static/style.css\">

</head>

<body>
<div class=\"container\">

    <div class=\"sidebar\">
        <div class=\"header\">
            <div class=\"list-item\">
                <a href=\"#\">
                    <span class=\"description-header\">BBPPMPV BOE</span>
                </a>
            </div>
            <div class=\"illustration\">
                <img src=\"/static/img/tut.png\" style=\"width:100px; height:100px;\" alt=\"\">
            </div>

        </div>
        <div class=\"main\">
            <div class=\"list-item\">
                <a href=\"#\">
                    <img src=\"/static/img/dashboard.png\" style=\"width:20px; height:20px;\" alt=\"\" class=\"icon\">
                </a>
                <span class=\"description\">Dashboard</span>
            </div>
            <div class=\"list-item\">
                <a href=\"#\">
                    <img src=\"/static/img/setting.png\" style=\"width:20px; height:20px;\" alt=\"\" class=\"icon\">
                </a>
                <span class=\"description\">Settings</span>
            </div>
            <div class=\"list-item\">
                <a href=\"#\">
                    <img src=\"/static/img/logout.png\" style=\"width:20px; height:20px;\" alt=\"\" class=\"icon\">
                </a>
                <span class=\"description\">Logout</span>
            </div>
        </div>
    </div>

    <div class=\"main-content\">
        <div id=\"menu-button\">
            <input type=\"checkbox\" id=\"menu-checkbox\">
            <label for=\"menu-checkbox\" id=\"menu-label\">
                <div id=\"hamburger\"></div>
            </label>
        </div>
        <div class=\"bodyHeader\"><h1>DEPARTEMEN TEKNOLOGI INFORMASI</h1></div>
        <div class=\"card-container\">
            <div class=\"main-card\">
                <h3>POWER CONTROL</h3>
                <div class=\"button-container\">
                    <button type=\"button\" name=\"button-settings\" id=\"Hijau1\" class=\"button button1\" value=\"on1\">ON
                    </button>
                    <button type=\"button\" name=\"button-settings\" id=\"Merah1\" class=\"button button2\" value=\"off1\">OFF
                    </button>
                </div>

            </div>

            <div class=\"main-card\">
                <h3>LAMP CONTROL</h3>
                <div class=\"button-container\">
                    <button type=\"button\" name=\"button-settings\" id=\"Hijau2\" class=\"button button1\" value=\"on2\">ON
                    </button>
                    <button type=\"button\" name=\"button-settings\" id=\"Merah2\" class=\"button button2\" value=\"off2\">OFF
                    </button>
                </div>
            </div>

            <div class=\"main-card\">
                <h3>ALARM CONTROL</h3>
                <div class=\"button-container\">
                    <button type=\"button\" name=\"button-settings\" id=\"Hijau3\" class=\"button button1\" value=\"on3\">ON
                    </button>
                    <button type=\"button\" name=\"button-settings\" id=\"Merah3\" class=\"button button2\" value=\"off3\">OFF
                    </button>
                </div>
            </div>

            <div class=\"main-card\">
                <h3>HIDRAULIC</h3>
                <div class=\"button-container\">
                    <button type=\"button\" name=\"button-settings\" id=\"Hijau4\" class=\"button button1\" value=\"on4\">ON
                    </button>
                    <button type=\"button\" name=\"button-settings\" id=\"Merah4\" class=\"button button2\" value=\"off4\">OFF
                    </button>
                </div>
            </div>
        </div>

        <div class=\"gauge-container\">
            <div class=\"gauge-card-1\">
                <h4>TEMPERATURE</h4>
                <div class=\"gauge\">
                    <div class=\"gauge__body\">
                        <div class=\"gauge__fill\"></div>
                        <div class=\"gauge__cover\"></div>
                    </div>
                </div>
            </div>
            <div class=\"gauge-card-2\">
                <h4>HUMIDITY</h4>
                <div class=\"gauge\">
                    <div class=\"gauge__body\">
                        <div class=\"gauge__fill\"></div>
                        <div class=\"gauge__cover\"></div>
                    </div>
                </div>
            </div>
            <div class=\"gauge-card-3\">
                <h4>ALTITUDE</h4>
                <div class=\"gauge\">
                    <div class=\"gauge__body\">
                        <div class=\"gauge__fill\"></div>
                        <div class=\"gauge__cover\"></div>
                    </div>
                </div>
            </div>
            <div class=\"gauge-card-4\">
                <h4>PRESSURE</h4>
                <div class=\"gauge\">
                    <div class=\"gauge__body\">
                        <div class=\"gauge__fill\"></div>
                        <div class=\"gauge__cover\"></div>
                    </div>
                </div>
            </div>
            <div class=\"gauge-card-5\">
                <h4>TEMPERATURE, HUMIDITY</h4>
                <canvas id=\"lineChart\"></canvas>
            </div>
            <div class=\"gauge-card-6\">
                <h4 style>NOISE LEVEL</h4>
                <div class=\"gauge\">
                    <div class=\"gauge__body\">
                        <div class=\"gauge__fill\"></div>
                        <div class=\"gauge__cover\"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<! -- SCRIPT -->
<script src=\"https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js\"></script>
<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.3.3/dist/chart.umd.min.js\"></script>
<script src=\"/static/script.js\"></script>
<script src=\"/static/kontrol.js\"></script>

</body>
</html>


"""
